# Generated by Django 2.2.6 on 2019-12-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('breed', models.TextField()),
                ('description', models.TextField()),
                ('arrival_date', models.TimeField(auto_now_add=True)),
                ('type_of_animal', models.CharField(choices=[('CA', 'Cat'), ('DO', 'Dog'), ('PA', 'Parrot')], default='CA', max_length=2)),
                ('photo', models.ImageField(height_field=300, upload_to='uploads/%Y/%m/%d/', width_field=300)),
                ('gender', models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='B', max_length=1)),
                ('availability_of_reference', models.BooleanField(default=False)),
                ('age', models.SmallIntegerField()),
            ],
        ),
    ]
