# Generated by Django 2.2.6 on 2019-12-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
    ]
