# Generated by Django 2.2.6 on 2019-12-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0002_remove_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, height_field=256, upload_to='uploads/%Y/%m/%d/', width_field=256),
        ),
    ]
