# Generated by Django 2.2.6 on 2019-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0005_auto_20191207_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
